import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className='grid grid-cols-3 gap-4 w-full p-4'>
          <div className='catalog-card shadow-lg bg-white rounded p-4'>
            dummy widget
          </div>
          <div className='catalog-card col-span-2 shadow-lg bg-white rounded p-4'>
            dummy widget
          </div>
          <div className='catalog-card col-span-2 shadow-lg bg-white rounded p-4'>
            dummy widget
          </div>
          <div className='catalog-card shadow-lg bg-white rounded p-4'>
            dummy widget
          </div>
          <div className='catalog-card shadow-lg bg-white rounded p-4'>
            dummy widget
          </div>
          <div className='catalog-card shadow-lg bg-white rounded p-4'>
            dummy widget
          </div>
          <div className='catalog-card shadow-lg bg-white rounded p-4'>
            dummy widget
          </div>
        </div>
      </div>
    </div>
  )
}

